### ISSUE TITLE
环境变量GOPROXY在go 1.15引入了新的分隔符

### ISSUE THREAD

**Issue by marjune163** [cloudnativebooks/cloud-native-go#28]
章节12.3.11-1，页码349：
本节末尾提到可以用`,`分割多个proxy，在1.15中如果想在出错时继续尝试下一个proxy，还可以使用`|`。感觉可以更新下？

**Comment by RainbowMango** [comment]
为什么关掉，我觉得说得很对啊。新版出来，特性有变化，是要更改。

**Comment by marjune163** [comment]
和这个重复了
https://github.com/cloudnativebooks/cloud-native-go/issues/29
显示提交失败，又发一遍，但其实发出来了
