### ISSUE TITLE
[勘误]反馈一个第1章第1.2节slice的勘误

### ISSUE THREAD

**Issue by lzw5399** [cloudnativebooks/cloud-native-go#38]
**问题描述**
p14 题目三
```go
func SliceExtend() {
  var slice []int
  s1 := append(slice, 1, 2, 3)
  s2 := append(s1, 4)
  fmt.Println(&s1[0] == &s2[0])
}
```
参考答案
> true

**如何找到这个错误**
- 章节：1.2
- 页码：14

**您认为应该如何？**
应该输出false(实际也是)。

**图片**
![](http://pic.codepie.fun/img/20210422171417.png)

**其他补充信息**

**Comment by lzw5399** [comment]
已经在下列找到具体的问题，go 1.16的新特性，将关闭
> https://github.com/RainbowMango/GoExpertProgramming/issues/88

**Comment by RainbowMango** [comment]
仍然非常感谢~
