### ISSUE TITLE
[第2版勘误]反馈一个第1章第1.3.2节的错别字

### ISSUE THREAD

**Issue by zilong-chen** [cloudnativebooks/cloud-native-go#49]
**问题描述**
27页倒数第三行错别字

**如何找到这个错误**
- 章节：1.3.2
- 页码：27

**您认为应该如何？**
`早查询操作中` 应为
`在查询操作中`

**图片**
如果有可能，尽量提供图片。
![1](https://github.com/cloudnativebooks/cloud-native-go/assets/108643101/8e6e4a79-a96b-4a16-b452-499123bad504)

**其他补充信息**

**Comment by RainbowMango** [comment]
感谢反馈，这个已经修复。可能你看的书出版日期比较早，这个已经修复了。对此纰漏表示歉意。

新版中已经修改为`查询操作中，可以给最多两个变量赋值，第一个为值xxxx`.

**Comment by zilong-chen** [comment]
我这边看的是第二版（2023年4月第1次印刷）， 可以跟编辑确认一下这个版本是否已经修正。

**Comment by RainbowMango** [comment]
我晕，我再跟编辑确认一下。先重新open这个issue便于跟踪。谢谢反馈

**Comment by RainbowMango** [comment]
您好，我已经把这个问题同步给编辑了，编辑反馈已在书稿中修改，下次重印时会修正。

再次感谢您的指正！
