### ISSUE TITLE
[第二版勘误]一些页面的问题

### ISSUE THREAD

**Issue by before80** [cloudnativebooks/cloud-native-go#50]
### 5页：“2）数据读写 ”一节中， 对 x, ok := <-ch 的论述

我个人觉得应该给出针对有缓冲区的管道、无缓冲区的管道的分开论述，毕竟无缓冲区的管道也可以进行  x, ok := <-ch。例如：

``` go

package main

import "fmt"

func main() {
	ch := make(chan int)

	go func() {
		ch <- 1
	}()

	x, ok := <-ch
	fmt.Printf("x=%v,ok=%v\n", x, ok) // x=1,ok=true
	close(ch)
	x, ok = <-ch
	fmt.Printf("x=%v,ok=%v\n", x, ok) // x=0,ok=false
}

```

这样才可以避免读者，在看到这一节的最后的一句“可以看到，只有管道已关闭且缓冲区中没有数据时，管道读取表达式返回的第二个变量才与管道关闭状态一致”时，误以为只有 “有缓冲区的”管道才可以这样操作，或认为“状态一致”只能在“有缓冲区的”管道中才会存在等。

[edit]
- 2023.10.21(@RainbowMango): 很遗憾的是修订时不允许做大的修改，只允许字符级别的修订，这个意见接受，只能留待下版再考虑了。

### 7页：“
因读阻塞的协程会被向管道写入数据的协程唤醒。
因写阻塞的协程会被从管道读数据的协程唤醒。
”

个人觉得可以多一个字“取”，或少一个字“入”，这样看起对仗工整一点。

改后的效果：
“
因读阻塞的协程会被向管道写入数据的协程唤醒。
因写阻塞的协程会被从管道读取数据的协程唤醒。
”
或
“
因读阻塞的协程会被向管道写数据的协程唤醒。
因写阻塞的协程会被从管道读数据的协程唤醒。
”

[edit]
- 2023.10.21(@RainbowMango): 确认可以把`入`字删除，因为写数据协程唤醒阻塞的协程时，实际上数据还没写入。已修改

### 18~19页：capacity 、 length  与 长度、容量有点混合使用

根据前后文，个人建议都使用 长度、容量。

[edit]:
- 2023.10.21(@RainbowMango): 使用`capacity`和`length`之处，上下文一般都有数据结构的描述，个人感觉使用英文单词更容易理解。如果我理解不对，还请指出具体修改点，感谢。

### 32页：第二段 ”而Go语言的map则在在负载因子达到6.5..."
多了一个“在”字，应该是”而Go语言的map则在负载因子达到6.5..."吧？

[edit]:
- 2023.10.21(@RainbowMango): 没有悬念，接受！感谢。

### 47页：“Name表示常量的名字，...”、“Value为常量值，与Name对应，...”

根据您在第46页中关于ValueSpec结构体的定义，这里的Name和Value应该修改成Names和Values吧？
若需要修改成Names和Values，则这两句可能需要修改成：
Names用于存储常量的名字，使用切片表示单行语句中声明的多个常量。
Values用于存储常量的值，与Names对应，表示常量的初始值。

[edit]:
- 2023.10.21(@RainbowMango)：已修改，修改如下
```diff
diff --git a/chapter01/5.3-iota_principle.md b/chapter01/5.3-iota_principle.md
index c04b328..2de63d0 100644
--- a/chapter01/5.3-iota_principle.md
+++ b/chapter01/5.3-iota_principle.md
@@ -29,9 +29,9 @@ const (
 上面的常量声明块中仅包括一行声明语句，该语句对应一个`ValueSpec`结构。

 - Doc 表示块注释，往往会出现在文档中的注释；
-- Name 表示常量的名字，使用切片表示单行语句中声明的多个常量；
-- Type 常量类型；
-- Value 常量值，与Name对应，表示常量的初始值；
+- Names 表示常量的名字，使用切片表示单行语句中声明的多个常量；
+- Type 表示常量类型；
+- Values 表示常量值，与Name对应，表示常量的初始值；
 - Comment 表示行注释
```
### 47页：“Type为量类型”

少了一个“常”字，应该是“Type为常量类型”吧？

[edit]:
- 2023.10.21(@RainbowMango)：已修改，修改同上。

### 51页：“在使用for-range遍历字符串时，每次迭代将返回字符UTF-8编码的首个字节下标及字节值，...”

这里的“字节值”，需要修改成“字符值”。

[edit]:
- 2023.10.21(@RainbowMango): 接受，已修改，同时也稍改了该句描述。
```diff
diff --git a/chapter01/6.2-string_usecase.md b/chapter01/6.2-string_usecase.md
index 7bd4422..5b9316a 100644
--- a/chapter01/6.2-string_usecase.md
+++ b/chapter01/6.2-string_usecase.md
@@ -88,7 +88,7 @@ func StringToByte() {
 #### 2.1 UTF编码
 string使用8比特字节的集合来存储字符，而且存储的是字符的UTF-8编码，例如每个汉字字符的UTF-8编码将占用多个字节。

-在使用for-range遍历字符串时，每次迭代将返回字符UTF-8编码的首个字节下标及字节值，这意味着下标可能不连续。
+在使用for-range遍历字符串时，每次迭代将返回字符的UTF-8编码首个字节下标及字符值，这意味着下标可能不连续。^M
 比如下面的函数：

```

### 51页：“字符串不支持取地址操作，也就无法修改字符串的值，...”

我想您要表达的是：对一个字符串的元素进行取地址操作。（ps: 这里的元素一说，我是看了go语言规范[String types一节](https://go.dev/ref/spec#String_types)中的“It is illegal to take the address of such an element; if s[i] is the i'th byte of a string, &s[i] is invalid.”）。所以我觉得这里是有一点问题。字符串是可以进行取地址操作，例如：

``` go
package main

import "fmt"

func main() {
	s := "你好世界！你好中国"
	fmt.Printf("%p\n", &s)

	s1 := s[0]
	fmt.Printf("%p\n", &s1)

	// fmt.Printf("%p\n", &s[0]) // 编译报错：invalid operation: cannot take address of s[0] (value of type byte)
}

```

[edit]:
- 2023.10.21(@RainbowMango): 已修改。
```diff
diff --git a/chapter01/6.2-string_usecase.md b/chapter01/6.2-string_usecase.md
index 5b9316a..d090b06 100644
--- a/chapter01/6.2-string_usecase.md
+++ b/chapter01/6.2-string_usecase.md
@@ -115,7 +115,7 @@ s := "Hello"
 &s[0] = byte(104) // 非法
 s = "hello" // 合法
-字符串不支持取地址操作，也就无法修改字符串值，上面的语句中会有编译错误：
+字符串元素不支持取地址操作，也就无法修改字符串值，上面的语句中会有编译错误：
```

### 56页：“string也可以方便地转成byte切片示：”

这里多了一个“示”字。

[edit]:
- 2023.10.21(@RainbowMango): 这里可能是编辑老师手误，书稿没问题，我会同步给出版社，感谢。

### 58页：编译器会识别如下临时场景的第二条：字符串拼接，如"<" + "string(b)"  + ">"

这里我想不用在string(b)的前后加上双引号。

[edit]:
- 2023.10.21(@RainbowMango): 已修改，感谢。

### 60页：题目三 选项C “sync.Map可以存储不同类型的键值对，这是它相对于原生map在灵活性方面的优势。”

选项C看起来也是对的。若是对的，则题目三应该是一个多选题。

[edit]:
- 2023.10.21(@RainbowMango): 实际上存储不同类型不是优势，而是陷阱。

### 60页：最后一段 “sync.Map的数据结构中包含了锁，所以它不同在函数间传递”

其中的“它不同”应该是“它不能”吧？

[edit]:
- 2023.10.21(@RainbowMango): 已修改。

### 62页：使用要点的第一点：“1）特定场景下性能够提升”

这句看起好像少了一个“能”，但多一个“能”字看起来有点奇怪，我觉得可以把“够”字换成“可”字。

[edit]:
- 2023.10.21(@RainbowMango): 已修改。`特定场景下可提升性能`

### 75页：“当select的多个case语句中的管道均阻塞时，整个select语句也会陷入阻塞（没有default语句的情况下），直到任意一个管道解除阻塞。”

根据您前文的描述，这里的“多个case语句中”，我觉得，应该要修改成“全部case语句中”，多个的意思是大于1个，但并不表示全部的意思。例如：

``` go
package main

import "fmt"

func SelectForChan(c1 chan int, c2 chan int, c3 chan int) {
	select {
	case d := <-c1:
		fmt.Printf("c1 received: %d\n", d)
	case c1 <- 1:
		fmt.Printf("c1 sent %d\n", 1)
	case d := <-c2:
		fmt.Printf("c2 received: %d\n", d)
	case c2 <- 2:
		fmt.Printf("c2 sent %d\n", 2)
	case d := <-c3:
		fmt.Printf("c3 received: %d\n", d)
	case c3 <- 3:
		fmt.Printf("c3 sent %d\n", 3)
	}
}

func main() {
	ch1 := make(chan int)
	ch2 := make(chan int)
	ch3 := make(chan int, 1)

	SelectForChan(ch1, ch2, ch3)
}

```

[edit]:
- 2023.10.21(@RainbowMango): 已修改。

### 84页：题目四的答案

您在第86页给出的答案是D（函数触发panic），但根据您第86页的描述似乎答案应该是C（函数打印hi后阻塞）

但这道题，我觉得，可能还跟怎么调用该函数有关。例如：

``` go
package main

import (
	"fmt"
	"time"
)

func RangeTimer() {
	defer func() {
		if r := recover(); r != nil {
			fmt.Println("panic: ", r)
		}
	}()

	t := time.NewTimer(time.Second)

	for _ = range t.C {
		fmt.Println("hi")
	}
}

func main() {
	defer func() {
		if r := recover(); r != nil {
			fmt.Println("panic: ", r)
		}
	}()

	go RangeTimer()

	time.Sleep(20 * time.Second)
}

```
将会打印出“hi”, 同时没有发生panic

如果是以下方式调用（少了 在 RangeTimer 前面使用 go关键字）：

``` go
package main

import (
	"fmt"
	"time"
)

func RangeTimer() {
	defer func() {
		if r := recover(); r != nil {
			fmt.Println("panic: ", r)
		}
	}()

	t := time.NewTimer(time.Second)

	for _ = range t.C {
		fmt.Println("hi")
	}
}

func main() {
	defer func() {
		if r := recover(); r != nil {
			fmt.Println("panic: ", r)
		}
	}()

	RangeTimer()

	time.Sleep(20 * time.Second)
}


```

则会打印出“hi”,之后报错：fatal error: all goroutines are asleep - deadlock!

所以这里我也不知道最后的答案是哪一个了。

[edit]:
- 2023.10.21(@RainbowMango): 这个答案为C。这个是单单从函数角度看的，如果整个程序都阻塞，运行时会panic。

### 86页：2.2.2节 第二段 “由于range可以给循环变量赋值，使其起来好像函数返回一样”

“使其起来好像”应该是少了一个“看”字，应该是“使其看起来好像”吧？

[edit]:
- 2023.10.21(@RainbowMango): 又一个编辑错误, 待同步给编辑老师.

### 88页：“rune类型，它仅代表Unicode编码的1个字节：”

这里的表述好像有点问题，我看其他文章或博客，说rune表示的是一个Unicode码点或字符。

[edit]:
- 2023.10.21(@RainbowMango): 已修改，谢谢。确实是字符。

### 103页：“编写过C语言程序的读者肯定知道malloc()方法...”

这里malloc()在C语言中应该是函数，面向对象的编程语言或类似面向对象的编程语言中才有“方法”，所以这里应该是需要将“方法“这两字修改成“函数”吧？
[edit]:
- 2023.10.21(@RainbowMango): 已修改，谢谢。确实函数更严谨些。

### 129页：““坐等协程”可能会永远无法被唤醒而产生列锁，...”

这里“列锁”，应该需要修改成“死锁”吧？

[edit]:
- 2023.10.21(@RainbowMango): 已修改，谢谢。

### 131页：content.Backgroud

少了一个字母“n”，应该是content.Background

[edit]:
- 2023.10.21(@RainbowMango): 已修改，谢谢。

### 132页：“context包中定义了一个公用的emptCtx全局变量”

emptCtx少了一个字母“y”，应该是emptyCtx吧？
[edit]:
- 2023.10.21(@RainbowMango): 已修改，谢谢。

### 132页：“context包提供了四个方法创建不同类型的context，使用这四个方法时如果没有父context，则需要出入backgroud，即将backgroud作为其父节点”

其中的backgroud，应该都是少了一个字母“n”，应该是background吧？

[edit]:
- 2023.10.21(@RainbowMango): 已修改，谢谢。
 
### 133页：“struct cancelCtx、timerCtx、valueCtx都继承于Context...”

这里的“继承于”，与您在第36页提到的“Go语言的struct与其他编程语言的class有些类似可以定义字段和方法，但是不可以继承。”，有一些矛盾。我看了官方的的 [FAQ-Why is there no type inheritance?](https://go.dev/doc/faq#inheritance)，以及 [FAQ-Why doesn't Go have "implements" declarations?](https://go.dev/doc/faq#implements_interface)，说法和您在第36页说的一致。所以我想第133页的“继承于”应该修改成“实现了”吧？

[edit]:
- 2023.10.21(@RainbowMango): 已修改，谢谢。

### 134页：“实际上，WithCancel()返回的第二个用于cancel context的方法正是此cancel()。”

我看了go1.11源码中的WithCancel：
``` go
func WithCancel(parent Context) (ctx Context, cancel CancelFunc) {
	c := newCancelCtx(parent)
	propagateCancel(parent, &c)
	return &c, func() { c.cancel(true, Canceled) }
}
```

go 1.20.6的源码中的WithCancel：
``` go
func WithCancel(parent Context) (ctx Context, cancel CancelFunc) {
	c := withCancel(parent)
	return c, func() { c.cancel(true, Canceled, nil) }
}
```

感觉这句话好像有点问题，我个人觉得可以修改成：“实际上，WithCancel()返回的第二个值的匿名函数中用于cancel context的方法正是此cancel()。”

[edit]:
- 2023.10.21(@RainbowMango): 这个暂时不改吧，没想到如何更简洁的表达。

### 135页：“返回cancelCtx实例和cancel方法。”

若134页改成使用到“匿名函数”，似乎这里就需要修改成“返回cancelCtx实例和cancel匿名函数。”

### 141页：“这里有一个细节需要关注，即当前context查找不到key时，会向父节点查找，如果查询不到则最终返回interface{}。”

“最后返回interface{}”，我看了go1.20.6的源码，其返回的是nil。不知道这里的interface{}，是不是应该写成nil？

[edit]:
- 2023.10.21(@RainbowMango): 这个暂时不改吧。context花费了10页篇幅，感觉过于繁琐，期望下一版能优化掉。

### 147页 “协程调度机制中的Process数量要大于1”

我看了您在97页中标注的是“P（processor）：处理器...”，而这里写的是“Process”，我想应该是“Processor”吧？

[edit]:
- 2023.10.21(@RainbowMango): 已修改，谢谢。

### 156页：“题目一：如何判断Foo结构体中的两个变量是否相等？...” 和 “题目二：如何判断空接口类型中的两个变量是否相等？”

我个人感觉，这两句话读起来有点奇怪的感觉（句子表达中含有集合的概念）。我觉得可以修改成：

“题目一：如何判断两个Foo结构体变量是否相等？...” 和 “题目二：如何判断两个空接口类型变量是否相等？”

[edit]:
- 2023.10.21(@RainbowMango): 已修改，谢谢。

### 165页：“测试函数命名规则为TestXxx，其中Test为单元测试的固定开头，go test只会执行以此开头的方法。”

这句的后面部分“go test只会执行以此开头的方法”表述有点不对，和您在171页中的写到的“执行测试可以使用go test，此时该目录下的其他测试文件也会一并执行。”有点矛盾了。

还有一点，就是这句以“测试函数”开始、以“方法”结束，好像说的都是同一个事物，是否应该统一一下说法。

可以直接去除掉“只会”中的“只”，将方法修改为“测试函数”，修改后的效果：
“测试函数命名规则为TestXxx，其中Test为单元测试的固定开头，go test会执行以此开头的测试函数。”

[edit]:
- 2023.10.21(@RainbowMango): 已修改，谢谢。

### 166页 最底下的代码中的第一个注释 “//MakeSliceWithPreAlloc，不预分配内存”

应该需要修改为“//MakeSliceWithoutAlloc，不预分配内存”吧？

[edit]:
- 2023.10.21(@RainbowMango): 已修改，谢谢。

### 170~171页：页面中的"OutPut"中P大写的问题

目前我只在Windows系统上进行测试，OutPut中的P大写，是不影响示例测试的，但不知道在Linux中的是否会出现问题。
根据[pkg testing](https://pkg.go.dev/testing#hdr-Examples) 的说明给出的是："Output: " 和 "Unordered output:"。

[edit]:
- 2023.10.21(@RainbowMango): 已修改，谢谢。源码仓库里跑过CI，没问题，但为了严谨，还是改成`Output`。

### 215页 “使用命令go get golang.org/x/pref/cmd/benchstat即可快捷安装benchstat...”

从 Go 1.16 开始，go install 是推荐用于构建和安装程序的命令。
-d 标志告诉 go get 不要构建或安装包。当使用 -d 时，go get 将只管理 go.mod 中的依赖项。
在没有-d的情况下使用go get来构建和安装包已经被废弃了（从Go 1.17开始）。
在 Go 1.18 中，-d 将永远被启用。

所以这里建议标注下不同版本的安装方式。go 1.16 是2021年2月16日发布的。
对于大于等于 go 1.16，应该建议使用以下方式安装：

`go install golang.org/x/pref/cmd/benchstat@latest` 

[edit]:
- 2023.10.21(@RainbowMango): 已修改，谢谢。同时 `pref` 应该为 p`er`f。这里直接修改为 `install`了。不想维护老版本的用法了，随时间推移，旧版本没必要再记了。

### 219页 题目二  “答案为B和D”

这道题根据您下面的描述，应该也是为了说“答案为B和C”的！

以下运行后的结果
``` go
package main

import (
	"errors"
	"fmt"
)

func main() {
	err := errors.New("not found")
	err1 := fmt.Errorf("some context: %v", err)
	err2 := fmt.Errorf("some context: %w", err)

	fmt.Printf("err1的类型：%T\n", err1)
	fmt.Printf("err1的类型：%T\n", err2)

	fmt.Println(err1.Error())
	fmt.Println(err2.Error())

	if err1.Error() == err2.Error() {
		fmt.Println("eq")
	} else {
		fmt.Println("neq")
	}
}
// Output:
//err1的类型：*errors.errorString
//err1的类型：*fmt.wrapError
//some context: not found
//some context: not found
//eq
```
所以这道选择题最终的答案应该是“B和C”吧？

[edit]:
- 2023.10.21(@RainbowMango): 又一处编辑错误 :(

### 253页：“触发panic函数中的defer语句是否会执行”

是否应该在panic后加一个“后”字，应该是“触发panic后函数中的defer语句是否会执行”吧？

[edit]:
- 2023.10.21(@RainbowMango): 已修改。谢谢。

### 280页： 第二个代码块用于演示公交车发车场景的代码

应该是少了在 `ticker := time.NewTicker(5 * time.Minute)` 之后一行加上 `defer ticker.Stop()` 吧？

[edit]:
- 2023.10.21(@RainbowMango): 您说得对，应该加个defer更严谨，此处由于函数不会退出，所以也不至于泄露。

### 303页：“然而，虽然应用很广泛，但并代表大家对它有深刻的认识”

这里，我猜测，是需要在“但并”后面加上一个“不”字，应该是“然而，虽然应用很广泛，但并不代表大家对它有深刻的认识”

[edit]:
- 2023.10.21(@RainbowMango): 已修改，谢谢

### 314页：“大多数情况下，Go编译器根据传递的参数可以自动推导出类型”

虽然有些博客，或文章，弱化了形参和实参的称法，但我个人觉得还是有必要区分下。故这里我觉得应该是“大多数情况下，Go编译器根据传递的实参可以自动推导出类型”吧？

[edit]:
- 2023.10.21(@RainbowMango): 已修改，谢谢

### 349页：第一段 “例如，要引用**module** module github.com/rehongcai/indirect中的内容时，其import路径需要为import github.com/renhongcai/indirect”

多了一个加粗显示的"module"，以及少了在import 后面的一对双引号，应该是“例如，要引用 module github.com/rehongcai/indirect中的内容时，其import路径需要为import "github.com/renhongcai/indirect" ” 吧？

[edit]:
- 2023.10.21(@RainbowMango): 已修改，谢谢

### 358页：中间部分 “go.mod只需记录直接依赖的依赖包版本，只在依赖包版本不包含go.mod文件时才会记录间接依赖包版本，...”

根据您在345页的表述，这里应该还少了345页描述中的第二种情况吧？所以我在想是不是可以在“只在依赖包版本不包含”后加上“在其”两个字，完整的表述是“go.mod只需记录直接依赖的依赖包版本，只在依赖包版本不包含在其go.mod文件时才会记录间接依赖包版本，...”  ？

[edit]:
- 2023.10.21(@RainbowMango): 这个暂时不改吧，事实上go.mod go.sum文件在最近的几个版本里还是有微调的，这个留待下一版再一并优化吧。

目前，我只读到 358页 ，后续阅读遇到问题再来请教下您。

不好意思，没按照您要求的格式给您的第二版书提出勘误，望见谅！

**Comment by RainbowMango** [comment]
感谢您的反馈，我稍后会逐一确认并反馈给您。

**Comment by before80** [comment]
您好，好久没看到您的反馈了，图书馆借的书，马上就要到期了

**Comment by RainbowMango** [comment]
不好意思，最近有点忙还没来得及确认。 争取下周确认吧。

**Comment by RainbowMango** [comment]
@before80 问题已确认。后面我会逐一修改并在这里反馈。

通过反馈信息可以看出阅读得非常仔细，我很感激您的耐心给出如此详细的勘误。
请留个联系地址，我给您寄送一本。（如果担心隐私信息泄露，可以给我发邮件 qdurenhongcai@gmail.com）.

**Comment by before80** [comment]
太好了，感谢您！给您发了一封邮件。

**Comment by RainbowMango** [comment]
图书已经寄出，本周应该能到，到货后请留言, 也请继续阅读并帮忙找出更多纰漏 :)

**Comment by before80** [comment]
好的，感谢您！我继续在这个issue上进行啦

**Comment by before80** [comment]
您好，您寄的书已收到，感谢!

**Comment by RainbowMango** [comment]
OK. 那就辛苦您继续看吧 :)

**Comment by RainbowMango** [comment]
@before80 非常非常感谢您提供的勘误信息，绝大部分修改都已接受。

如果有新的意见，请继续回复或者另开一个issue。
