### ISSUE TITLE
【第二版】for-range热身测验-题目二

### ISSUE THREAD

**Issue by YLLL-ux** [cloudnativebooks/cloud-native-go#51]
**问题描述**
```go
// 题目二： 引用循环变量下标
func PrintSlice() {
	s := []int{1, 2, 3}
	var wg sync.WaitGroup
	wg.Add(len(s))
	for _, v := range s {
		go func() {
			fmt.Println(v)
			wg.Done()
		}()
	}
	wg.Wait()
}
```

// **Output并不是 3, 3, 3**，三个协程会从数组中随机执行

**如何找到这个错误**
- 章节：第二章
- 页码：P85

**您认为应该如何？**
=== RUN   TestPrintSlice
3
2
1
--- PASS: TestPrintSlice (0.00s)

**图片**
如果有可能，尽量提供图片。

**其他补充信息**

**Comment by RainbowMango** [comment]
收到，感谢。我会尽快确认并处理。

**Comment by RainbowMango** [comment]
我猜你应该用的是Go1.22+. 

Go1.22版本针对`for`循环做了优化，循环变量将不再共享，每个loop创建一个新的变量，避免因为变量共享而引起非预期的行为。
引自[Go1.22 release notes](https://go.dev/doc/go1.22):
> Previously, the variables declared by a "for" loop were created once and updated by each iteration. In Go 1.22, each iteration of the loop creates new variables, to avoid accidental sharing bugs. The [transition support tooling](https://go.dev/wiki/LoopvarExperiment#my-test-fails-with-the-change-how-can-i-debug-it) described in the proposal continues to work in the same way it did in Go 1.21.

**Comment by RainbowMango** [comment]
因为第二版内容更新至1.19，行为还停留在1.19版本。所以这个问题留待第三版再修改吧。届时将删除这个题目。因为这个易出错点已经从语言层面杜绝，这个题目也没有存在的价值了。

**Comment by YLLL-ux** [comment]
> 我猜你应该用的是Go1.22+.
> 
> Go1.22版本针对`for`循环做了优化，循环变量将不再共享，每个loop创建一个新的变量，避免因为变量共享而引起非预期的行为。 引自[Go1.22 release notes](https://go.dev/doc/go1.22):
> 
> > Previously, the variables declared by a "for" loop were created once and updated by each iteration. In Go 1.22, each iteration of the loop creates new variables, to avoid accidental sharing bugs. The [transition support tooling](https://go.dev/wiki/LoopvarExperiment#my-test-fails-with-the-change-how-can-i-debug-it) described in the proposal continues to work in the same way it did in Go 1.21.

是的，我使用的是1.22版本

**Comment by YLLL-ux** [comment]
那我这里关闭了

**Comment by RainbowMango** [comment]
好的，再次感谢反馈。
